name: pytorch367_cpu
channels:
  - pytorch
  - defaults
dependencies:
  - cpuonly=1.0
  - python=3.6.7
  - pytorch=1.2.0
  - torchvision=0.4.0
  - sphinx
  - sphinx-autoapi
  - sphinxcontrib-napoleon
  - sphinx_rtd_theme