name: pytorch367_cpu
channels:
  - pytorch
  - defaults
dependencies:
  - blas=1.0
  - certifi=2019.6.16
  - cffi=1.12.3
  - cpuonly=1.0
  - freetype=2.9.1
  - intel-openmp=2019.4
  - jpeg=9b
  - libpng=1.6.37
  - libtiff=4.0.10
  - mkl=2019.4
  - mkl-service=2.0.2
  - mkl_fft=1.0.14
  - mkl_random=1.0.2
  - ninja=1.9.0
  - numpy=1.16.4
  - numpy-base=1.16.4
  - olefile=0.46
  - pillow=6.1.0
  - pip=19.2.2
  - pycparser=2.19
  - python=3.6.7
  - pytorch=1.2.0
  - setuptools=41.0.1
  - six=1.12.0
  - sqlite=3.29.0
  - tk=8.6.8
  - torchvision=0.4.0
  - wheel=0.33.4
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - absl-py==0.8.0
    - alabaster==0.7.12
    - argcomplete==1.10.0
    - astroid==2.2.5
    - atomicwrites==1.3.0
    - attrs==19.1.0
    - babel==2.7.0
    - bleach==3.1.0
    - chardet==3.0.4
    - colorama==0.4.1
    - colorlog==3.2.0
    - coverage==4.5.4
    - cycler==0.10.0
    - decorator==4.4.0
    - docutils==0.15.2
    - grpcio==1.23.0
    - idna==2.8
    - imageio==2.5.0
    - imagesize==1.1.0
    - importlib-metadata==0.20
    - jinja2==2.10.1
    - joblib==0.13.2
    - kiwisolver==1.1.0
    - lazy-object-proxy==1.4.2
    - markdown==3.1.1
    - markupsafe==1.1.1
    - matplotlib==3.1.1
    - more-itertools==7.2.0
    - networkx==2.3
    - nox==2019.8.20
    - onnx==1.5.0
    - packaging==19.1
    - pandas==0.25.1
    - pkginfo==1.5.0.1
    - pluggy==0.12.0
    - pockets==0.7.2
    - protobuf==3.9.1
    - py==1.8.0
    - pygments==2.4.2
    - pyparsing==2.4.2
    - pytest==5.1.2
    - pytest-cov==2.7.1
    - python-dateutil==2.8.0
    - pytz==2019.2
    - pywavelets==1.0.3
    - pyyaml==5.1.2
    - readme-renderer==24.0
    - requests==2.22.0
    - requests-toolbelt==0.9.1
    - scikit-image==0.15.0
    - scikit-learn==0.21.3
    - scipy==1.3.1
    - sklearn==0.0
    - snowballstemmer==1.9.1
    - sphinx==2.2.0
    - sphinx-autoapi==1.1.0
    - sphinx-rtd-theme==0.4.3
    - sphinxcontrib-applehelp==1.0.1
    - sphinxcontrib-devhelp==1.0.1
    - sphinxcontrib-dotnetdomain==0.4
    - sphinxcontrib-golangdomain==0.2.0.dev0
    - sphinxcontrib-htmlhelp==1.0.2
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-napoleon==0.7
    - sphinxcontrib-qthelp==1.0.2
    - sphinxcontrib-serializinghtml==1.1.3
    - tensorboard==1.14.0
    - tensorboardx==1.8
    - tqdm==4.35.0
    - twine==1.13.0
    - typed-ast==1.4.0
    - typing==3.7.4.1
    - typing-extensions==3.7.4
    - unidecode==1.1.1
    - urllib3==1.25.3
    - virtualenv==16.7.5
    - wcwidth==0.1.7
    - webencodings==0.5.1
    - werkzeug==0.15.6
    - wrapt==1.11.2
    - zipp==0.6.0
