name: pytorch367_cpu
channels:
  - pytorch
  - defaults
dependencies:
  - blas=1.0
  - certifi=2019.6.16
  - cffi=1.12.3
  - cpuonly=1.0
  - freetype=2.9.1
  - intel-openmp=2019.4
  - jpeg=9b
  - libpng=1.6.37
  - libtiff=4.0.10
  - mkl=2019.4
  - mkl-service=2.0.2
  - mkl_fft=1.0.14
  - mkl_random=1.0.2
  - ninja=1.9.0
  - numpy=1.16.4
  - numpy-base=1.16.4
  - olefile=0.46
  - pillow=6.1.0
  - pip=19.2.2
  - pycparser=2.19
  - python=3.6.7
  - pytorch=1.2.0
  - setuptools=41.0.1
  - six=1.12.0
  - sqlite=3.29.0
  - tk=8.6.8
  - torchvision=0.4.0
  - wheel=0.33.4
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.3.7
