__name__ = "trw"
__version__ = "0.0.1"
__description__ = "Train, test, debug and optimize PyTorch models"
__url__ = "https://github.com/civodlu/trw"
__author__ = "Civodlu"
__email__ = "civodlu@gmail.com"
__license__ = "MIT"
